// <auto-generated />
namespace StatTrackr.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class StatLineIdnoidentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StatLineIdnoidentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201503110501014_Stat Line Id no identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
